"""
Base LLM Interface Module
Defines abstract interface for language model clients

Supports multiple providers (OpenAI, Anthropic) through polymorphism.
All agent classes depend on this interface, not specific implementations.
"""
from abc import ABC, abstractmethod
from typing import List, Dict, Any, AsyncIterator


class BaseLLMClient(ABC):
    """
    Abstract base class for Language Model clients
    
    Defines the interface that all LLM implementations must follow.
    Allows agents to work with any LLM provider without code changes.
    """
    
    @abstractmethod
    async def complete(
        self,
        messages: List[Dict[str, str]],
        system_prompt: str = None,
        temperature: float = 0.0,
        max_tokens: int = 4000
    ) -> str:
        """
        Generate text completion from messages
        
        Args:
            messages: List of message dicts with 'role' and 'content' keys
                     Example: [{"role": "user", "content": "Hello"}]
            system_prompt: Optional system prompt to guide model behavior
            temperature: Sampling temperature (0.0 = deterministic, 1.0 = creative)
            max_tokens: Maximum tokens to generate in response
            
        Returns:
            Complete generated text response
            
        Raises:
            Exception: If API call fails
        """
        pass
    
    @abstractmethod
    async def stream_complete(
        self,
        messages: List[Dict[str, str]],
        system_prompt: str = None,
        temperature: float = 0.0,
        max_tokens: int = 4000
    ) -> AsyncIterator[str]:
        """
        Stream text completion chunk by chunk
        
        Useful for real-time display in chat interfaces.
        Yields text chunks as they're generated by the model.
        
        Args:
            messages: List of message dicts (same as complete())
            system_prompt: Optional system prompt
            temperature: Sampling temperature
            max_tokens: Maximum tokens to generate
            
        Yields:
            Text chunks as strings
            
        Raises:
            Exception: If streaming fails
        """
        pass
    
    @abstractmethod
    def get_provider_name(self) -> str:
        """
        Get the name of the LLM provider
        
        Returns:
            Provider name (e.g., 'openai', 'anthropic')
        """
        pass
    
    @abstractmethod
    def get_model_name(self) -> str:
        """
        Get the specific model being used
        
        Returns:
            Model name (e.g., 'gpt-4', 'claude-3-5-sonnet-20241022')
        """
        pass